// Jedinstveni nazivi i ikonice automatskih generatora koje dele sve admin forme.
export const NAZIVI_GENERISANIH_OBLASTI: Record<string, string> = {
  'brojevi-do-100-2': 'Brojevi do 100', 'sabiranje-2': 'Sabiranje', 'oduzimanje-2': 'Oduzimanje',
  'mnozenje-2': 'Množenje', 'deljenje-2': 'Deljenje',
  'kombinovane-operacije-2': 'Kombinovane računske operacije', 'jednacine-2': 'Jednačine',
  'delovi-celine-2': 'Delovi celine', 'novac-2': 'Novac', 'rimski-brojevi-2': 'Rimski brojevi',
  'nizovi-2': 'Nizovi', 'tabele-i-dijagrami-2': 'Tabele i dijagrami',
  'geometrija-2': 'Geometrija', 'merenje-2': 'Merenje i mere',
  sabiranje: 'Sabiranje', oduzimanje: 'Oduzimanje', mnozenje: 'Množenje', deljenje: 'Deljenje',
  'kombinovane-operacije': 'Kombinovane računske operacije', 'poredjenje-brojeva': 'Poređenje brojeva',
  'nizovi-i-obrasci': 'Nizovi i obrasci', 'obim-i-merenje': 'Obim i merenje dužine',
  'merne-jedinice': 'Merne jedinice', novac: 'Novac', 'rimski-brojevi': 'Rimski brojevi',
  jednacine: 'Jednačine', nejednacine: 'Nejednačine',
  'veliki-brojevi-4': 'Veliki brojevi', 'sabiranje-4': 'Sabiranje', 'oduzimanje-4': 'Oduzimanje',
  'mnozenje-4': 'Množenje', 'deljenje-4': 'Deljenje', 'kombinovane-operacije-4': 'Kombinovane računske operacije',
  'jednacine-4': 'Jednačine', 'nejednacine-4': 'Nejednačine', 'povrsina-4': 'Površina',
  'zapremina-4': 'Zapremina', 'geometrijska-tela-4': 'Geometrijska tela', 'razlomci-4': 'Razlomci',
  'decimalni-brojevi-4': 'Decimalni brojevi',
  'prirodni-brojevi-5': 'Prirodni brojevi i izrazi', 'deljivost-5': 'Deljivost',
  'skupovi-i-logika-5': 'Skupovi i logika', 'prosti-brojevi-5': 'Prosti brojevi',
  'nzd-i-nzs-5': 'NZD i NZS', 'tacke-prave-i-duzi-5': 'Tačke, prave i duži',
  'kruznica-i-krug-5': 'Kružnica i krug', 'centralna-simetrija-i-translacija-5': 'Centralna simetrija i translacija',
  'uglovi-5': 'Uglovi', 'razlomci-5': 'Razlomci', 'decimalni-brojevi-5': 'Decimalni brojevi',
  'operacije-sa-razlomcima-5': 'Operacije sa razlomcima', 'jednacine-i-nejednacine-5': 'Jednačine i nejednačine',
  'procenti-prosek-i-razmera-5': 'Procenti, prosek i razmera', 'obrada-podataka-5': 'Obrada podataka',
  'osna-simetrija-5': 'Osna simetrija',
  'srpski-vrste-reci': 'Vrste reči', 'srpski-gramatika': 'Gramatika', 'srpski-pravopis': 'Pravopis',
  'srpski-citanje': 'Čitanje i razumevanje', 'srpski-recnik': 'Rečnik',
  'srpski-gramatika-4': 'Gramatika', 'srpski-recnik-4': 'Rečnik', 'srpski-citanje-4': 'Čitanje i razumevanje',
  'srpski-gramatika-5': 'Gramatika', 'srpski-recnik-5': 'Rečnik', 'srpski-citanje-5': 'Čitanje i razumevanje',
  'pid-priroda-covek-drustvo-3': 'Priroda, čovek i društvo', 'pid-orijentacija-3': 'Orijentacija',
  'pid-proslost-3': 'Prošlost', 'pid-kretanje-3': 'Kretanje', 'pid-materijali-3': 'Materijali',
  'pid-beograd-3': 'Beograd — moj grad',
  'pid-odlike-srbije-4': 'Odlike Srbije', 'pid-covek-4': 'Čovek',
  'pid-materijali-4': 'Materijali', 'pid-proslost-srbije-4': 'Prošlost Srbije',
}

export const IKONE_GENERISANIH_OBLASTI: Record<string, string> = {
  'brojevi-do-100-2': '💯', 'sabiranje-2': '➕', 'oduzimanje-2': '➖',
  'mnozenje-2': '✖️', 'deljenje-2': '➗', 'kombinovane-operacije-2': '🧮',
  'jednacine-2': '🟰', 'delovi-celine-2': '🍕', 'novac-2': '💰',
  'rimski-brojevi-2': '🏛️', 'nizovi-2': '🔁', 'tabele-i-dijagrami-2': '📊',
  'geometrija-2': '📐', 'merenje-2': '📏',
  sabiranje: '➕', oduzimanje: '➖', mnozenje: '✖️', deljenje: '➗',
  'kombinovane-operacije': '🧮', 'poredjenje-brojeva': '⚖️', 'nizovi-i-obrasci': '🔁',
  'obim-i-merenje': '📐', 'merne-jedinice': '📏', novac: '💰', 'rimski-brojevi': '🏛️',
  jednacine: '🟰', nejednacine: '≠', 'veliki-brojevi-4': '🔢', 'sabiranje-4': '➕',
  'oduzimanje-4': '➖', 'mnozenje-4': '✖️', 'deljenje-4': '➗', 'kombinovane-operacije-4': '🧮',
  'jednacine-4': '🟰', 'nejednacine-4': '≠', 'povrsina-4': '▦', 'zapremina-4': '📦',
  'geometrijska-tela-4': '🧊', 'razlomci-4': '🍕', 'decimalni-brojevi-4': '🔟',
  'prirodni-brojevi-5': '🔢', 'deljivost-5': '🧩', 'skupovi-i-logika-5': '◉',
  'prosti-brojevi-5': '🔍', 'nzd-i-nzs-5': '🔗', 'tacke-prave-i-duzi-5': '📐',
  'kruznica-i-krug-5': '⭕', 'centralna-simetrija-i-translacija-5': '🔄', 'uglovi-5': '📏',
  'razlomci-5': '🍕', 'decimalni-brojevi-5': '🔟', 'operacije-sa-razlomcima-5': '➗',
  'jednacine-i-nejednacine-5': '🟰', 'procenti-prosek-i-razmera-5': '💯',
  'obrada-podataka-5': '📊', 'osna-simetrija-5': '🪞',
  'srpski-vrste-reci': '🔤', 'srpski-gramatika': '📚', 'srpski-pravopis': '✍️',
  'srpski-citanje': '📖', 'srpski-recnik': '🗣️', 'srpski-gramatika-4': '📚',
  'srpski-recnik-4': '🗣️', 'srpski-citanje-4': '📖',
  'srpski-gramatika-5': '📚', 'srpski-recnik-5': '🗣️', 'srpski-citanje-5': '📖',
  'pid-priroda-covek-drustvo-3': '🌿', 'pid-orijentacija-3': '🧭', 'pid-proslost-3': '⌛',
  'pid-kretanje-3': '🏃', 'pid-materijali-3': '🧪', 'pid-odlike-srbije-4': '🇷🇸',
  'pid-beograd-3': '🏙️',
  'pid-covek-4': '🧑', 'pid-materijali-4': '🧲', 'pid-proslost-srbije-4': '🏛️',
}
