import { napraviPidGenerator, type PidCinjenica, type PidOblast } from './zajednicko.ts'

function c(
  id: string, porodica: string, pitanje: string, tacan: string, netacni: readonly string[],
  tacnaTvrdnja: string, netacnaTvrdnja: string, objasnjenje: string, hint: string,
): PidCinjenica {
  return { id, porodica, pitanje, tacan, netacni, tacnaTvrdnja, netacnaTvrdnja, objasnjenje, hint }
}

export const BEOGRAD_3: PidOblast = {
  slug: 'pid-beograd-3',
  povezivanjeTekst: 'Poveži beogradsko mesto ili pojam sa odgovarajućim opisom.',
  cinjenice: [
    c('glavni-grad', 'polozaj-i-vode', 'Koji je glavni grad Srbije?', 'Beograd', ['Novi Sad', 'Niš', 'Kragujevac'],
      'Beograd je glavni grad Srbije.', 'Niš je glavni grad Srbije.',
      'Beograd je glavni grad Srbije i u njemu se nalaze važne državne ustanove.', 'Seti se grada na ušću Save u Dunav.'),
    c('dve-reke', 'polozaj-i-vode', 'Na ušću kojih reka se nalazi Beograd?', 'Save i Dunava', ['Drine i Save', 'Nišave i Južne Morave', 'Ibra i Zapadne Morave'],
      'Beograd se nalazi na ušću Save u Dunav.', 'Beograd se nalazi na ušću Drine u Savu.',
      'Sava se u Beogradu uliva u Dunav, ispod Beogradske tvrđave.', 'Jedna reka je Sava; priseti se u koju se uliva.'),
    c('smer-ulivanja', 'polozaj-i-vode', 'Koja se reka u Beogradu uliva u Dunav?', 'Sava', ['Drina', 'Tisa', 'Nišava'],
      'Sava se u Beogradu uliva u Dunav.', 'Dunav se u Beogradu uliva u Savu.',
      'Sava je pritoka Dunava. Mesto gde se jedna reka uliva u drugu zove se ušće.', 'Razlikuj reku koja se uliva od reke koja prima njenu vodu.'),
    c('avala', 'reljef-i-izletista', 'Koja se planina nalazi u okolini Beograda?', 'Avala', ['Tara', 'Kopaonik', 'Zlatibor'],
      'Avala je planina u okolini Beograda.', 'Avala je reka koja protiče kroz Beograd.',
      'Avala je planina u okolini Beograda i poznato izletište.', 'Na toj planini se nalazi Avalski toranj.'),
    c('savsko-jezero', 'reljef-i-izletista', 'Kako se zove jezero uz Adu Ciganliju?', 'Savsko jezero', ['Palićko jezero', 'Vlasinsko jezero', 'Đerdapsko jezero'],
      'Uz Adu Ciganliju nalazi se Savsko jezero.', 'Uz Adu Ciganliju nalazi se Palićko jezero.',
      'Savsko jezero je nastalo pregrađivanjem rukavca Save uz Adu Ciganliju.', 'Ime jezera podseća na reku uz koju je nastalo.'),
    c('kosutnjak', 'reljef-i-izletista', 'Koje beogradsko mesto je poznato po šumi i stazama za šetnju?', 'Košutnjak', ['Trg republike', 'Knez Mihailova ulica', 'Terazije'],
      'Košutnjak je beogradska šuma i izletište.', 'Košutnjak je trg bez drveća u centru Beograda.',
      'Košutnjak je šumski prostor u Beogradu, važan i za živi svet i za odmor ljudi.', 'Traži mesto sa mnogo drveća, a ne gradski trg ili ulicu.'),
    c('kalemegdan', 'znamenitosti', 'Kako se zove park uz Beogradsku tvrđavu?', 'Kalemegdan', ['Tašmajdan', 'Topčiderski park', 'Pionirski park'],
      'Park Kalemegdan nalazi se uz Beogradsku tvrđavu.', 'Park Kalemegdan nalazi se na vrhu Avale.',
      'Kalemegdan je park uz Beogradsku tvrđavu. Park i tvrđava nisu ista vrsta prostora.', 'Seti se parka iznad ušća Save u Dunav.'),
    c('pobednik', 'znamenitosti', 'Koji se poznati spomenik nalazi na Beogradskoj tvrđavi?', 'Pobednik', ['Spomenik Neznanom junaku', 'Spomenik knezu Mihailu', 'Spomenik Vuku Karadžiću'],
      'Spomenik Pobednik nalazi se na Beogradskoj tvrđavi.', 'Spomenik Pobednik nalazi se na vrhu Avale.',
      'Pobednik je spomenik na Beogradskoj tvrđavi, iznad ušća Save u Dunav, i jedan je od simbola grada.', 'Njegovo ime potiče od reči „pobeda”.'),
    c('avalski-toranj', 'znamenitosti', 'Na kojoj se planini nalazi Avalski toranj?', 'na Avali', ['na Tari', 'na Kopaoniku', 'na Zlatiboru'],
      'Avalski toranj nalazi se na Avali.', 'Avalski toranj nalazi se na Kopaoniku.',
      'Avalski toranj je građevina na Avali, dok je sama Avala prirodno uzvišenje.', 'Naziv tornja otkriva ime planine.'),
    c('singidunum', 'proslost-grada', 'Kako se Beograd zvao u rimsko doba?', 'Singidunum', ['Naissus', 'Sirmium', 'Viminacium'],
      'Beograd se u rimsko doba zvao Singidunum.', 'Beograd se u rimsko doba zvao Naissus.',
      'Singidunum je antičko ime Beograda. Stari nazivi pomažu nam da upoznamo prošlost grada.', 'Naziv počinje sa „Singi”.'),
    c('uloga-tvrdjave', 'proslost-grada', 'Čemu je Beogradska tvrđava prvenstveno služila u prošlosti?', 'odbrani grada', ['organizovanju avionskog saobraćaja', 'proizvodnji električne energije', 'prečišćavanju vode'],
      'Beogradska tvrđava je u prošlosti služila odbrani grada.', 'Beogradska tvrđava je sagrađena kao aerodrom.',
      'Zidine, kapije i kule tvrđave pomagale su u odbrani grada.', 'Razmisli zašto su građene visoke zidine i kule.'),
    c('stara-fotografija', 'proslost-grada', 'Šta možeš da saznaš poređenjem stare i nove fotografije iste beogradske ulice?', 'kako se izgled ulice menjao', ['kakvo će vreme biti sutra', 'koliko je dubok Dunav', 'koliko godina ima svako drvo u gradu'],
      'Stare fotografije pomažu da saznamo kako je Beograd nekada izgledao.', 'Stare fotografije Beograda pouzdano pokazuju kakvo će vreme biti sutra.',
      'Na fotografijama iste ulice iz različitih vremena možemo porediti zgrade, vozila i izgled prostora.', 'Uporedi ono što se na fotografijama može videti.'),
    c('narodni-muzej', 'kultura', 'Koja ustanova na Trgu republike čuva umetnička dela i predmete iz prošlosti?', 'Narodni muzej', ['Narodno pozorište', 'škola', 'pošta'],
      'Narodni muzej na Trgu republike čuva umetnička dela i predmete iz prošlosti.', 'Narodni muzej na Trgu republike služi prvenstveno slanju pisama.',
      'Muzej prikuplja, čuva i izlaže predmete koji nam pomažu da upoznamo kulturu i prošlost.', 'Seti se ustanove u kojoj razgledamo zbirke i izložbe.'),
    c('knez-mihailo', 'kultura', 'Kome je posvećen spomenik konjaniku na Trgu republike u Beogradu?', 'knezu Mihailu', ['Vuku Karadžiću', 'Nikoli Tesli', 'Svetom Savi'],
      'Na Trgu republike u Beogradu nalazi se spomenik knezu Mihailu na konju.', 'Spomenik konjaniku na Trgu republike posvećen je Nikoli Tesli.',
      'Spomenik knezu Mihailu nalazi se na Trgu republike, ispred Narodnog muzeja.', 'I poznata obližnja pešačka ulica nosi ime ovog kneza.'),
    c('cuvanje-spomenika', 'kultura', 'Kako čuvamo Beogradsku tvrđavu tokom posete?', 'čuvamo zidine i ne pišemo po njima', ['urezujemo imena u zidine', 'odnosimo kamenje kao suvenir', 'ostavljamo smeće pored kapija'],
      'Čuvanjem zidina Beogradske tvrđave čuvamo kulturno nasleđe.', 'Urezivanjem imena u zidine Beogradske tvrđave čuvamo kulturno nasleđe.',
      'Tvrđava je kulturno nasleđe. Čuvamo je tako što je ne oštećujemo i poštujemo pravila posete.', 'Razmisli kako da tvrđava ostane sačuvana i za buduće posetioce.'),
    c('plan-grada', 'orijentacija-u-gradu', 'Šta pomaže da pronađeš ulicu i put do muzeja u Beogradu?', 'plan grada sa nazivima ulica', ['kalendar', 'termometar', 'raspored časova'],
      'Plan Beograda sa nazivima ulica pomaže pri pronalaženju puta do muzeja.', 'Termometar pokazuje kojim ulicama stižemo do muzeja u Beogradu.',
      'Na planu grada prikazani su raspored i nazivi ulica, pa možemo da pronađemo put do odredišta.', 'Potreban ti je prikaz prostora, a ne vremena ili temperature.'),
    c('legenda-plana', 'orijentacija-u-gradu', 'Gde možeš proveriti šta znači znak za muzej na planu Beograda?', 'u legendi plana', ['na termometru', 'u kalendaru', 'na satu'],
      'Legenda plana objašnjava značenje znakova na planu Beograda.', 'Značenje znakova na planu Beograda proveravamo na termometru.',
      'Legenda objašnjava znakove kojima su na planu predstavljeni objekti, kao što su muzeji.', 'Potraži deo plana sa objašnjenjima znakova.'),
    c('knez-mihailova', 'orijentacija-u-gradu', 'Koja je poznata pešačka ulica u centru Beograda?', 'Knez Mihailova', ['Bulevar kralja Aleksandra', 'Kneza Miloša', 'Bulevar Mihajla Pupina'],
      'Knez Mihailova je poznata pešačka ulica u centru Beograda.', 'Knez Mihailova je reka koja protiče kroz Beograd.',
      'Knez Mihailova je pešačka ulica u centru Beograda i prepoznatljivo mesto za šetnju.', 'Njeno ime podseća na kneza čiji je spomenik na Trgu republike.'),
    c('mostovi', 'saobracaj', 'Zašto su mostovi preko Save i Dunava važni Beogradu?', 'povezuju delove grada na različitim obalama', ['zaustavljaju tok obe reke', 'pretvaraju reke u planine', 'služe samo kao ukras'],
      'Mostovi preko Save i Dunava povezuju delove Beograda na različitim obalama.', 'Mostovi preko Save i Dunava služe da potpuno zaustave tok reka.',
      'Mostovi omogućavaju prelazak preko reke i povezuju ljude, naselja i delove grada.', 'Zamisli kako bi prešao/prešla sa jedne obale na drugu.'),
    c('tramvaj', 'saobracaj', 'Koje vozilo gradskog prevoza u Beogradu se kreće po šinama na ulici?', 'tramvaj', ['autobus', 'automobil', 'bicikl'],
      'Beogradski tramvaji kreću se po šinama.', 'Beogradski autobusi kreću se po šinama.',
      'Tramvaj je vozilo gradskog prevoza koje se kreće po šinama; autobus se kreće kolovozom bez šina.', 'Potraži vozilo kome su za kretanje potrebne šine.'),
    c('javni-prevoz', 'saobracaj', 'Koji primer predstavlja korišćenje javnog gradskog prevoza u Beogradu?', 'vožnja gradskim autobusom', ['vožnja porodičnim automobilom', 'šetnja parkom', 'vožnja sopstvenog bicikla'],
      'Gradski autobus prevozi više putnika i deo je javnog prevoza u Beogradu.', 'Porodični automobil je vozilo javnog gradskog prevoza.',
      'Javni gradski prevoz namenjen je zajedničkom prevozu putnika, na primer autobusom ili tramvajem.', 'Razlikuj prevoz za građane od privatnog vozila jedne porodice.'),
    c('ratno-ostrvo', 'zastita-prirode', 'Zašto je važno čuvati prirodu Velikog ratnog ostrva u Beogradu?', 'zato što je stanište ptica i drugih živih bića', ['zato što tamo nema živih bića', 'da bi se smeće odlagalo uz reku', 'da bi se uništila sva gnezda'],
      'Veliko ratno ostrvo je važno stanište ptica i drugih živih bića.', 'Veliko ratno ostrvo nema značaja za živi svet Beograda.',
      'Veliko ratno ostrvo kod ušća Save u Dunav važno je za očuvanje prirode i staništa ptica.', 'Razmisli kome su potrebni drveće, voda i mirna mesta za gnežđenje.'),
    c('otpad-na-adi', 'zastita-prirode', 'Šta radiš sa praznom ambalažom posle užine na Adi Ciganliji?', 'odlažem je u odgovarajuću kantu ili nosim do nje', ['bacam je u Savsko jezero', 'ostavljam je u travi', 'guram je među korenje drveta'],
      'Odlaganjem ambalaže u odgovarajuću kantu čuvamo Adu Ciganliju.', 'Bacanjem ambalaže u Savsko jezero čuvamo Adu Ciganliju.',
      'Otpad ne ostavljamo u prirodi. Ako kanta nije u blizini, nosimo ga sa sobom do odgovarajuće kante.', 'Izaberi postupak posle koga priroda ostaje čista.'),
    c('ptice-u-parku', 'zastita-prirode', 'Kako posmatramo ptice i njihova gnezda u beogradskom parku?', 'mirno, sa odstojanja, bez diranja gnezda', ['tresemo granu sa gnezdom', 'uzimamo jaja iz gnezda', 'jurimo ptice da bi poletele'],
      'Ptice u beogradskim parkovima posmatramo bez uznemiravanja i diranja gnezda.', 'Uzimanje jaja iz gnezda pomaže pticama u beogradskim parkovima.',
      'Parkovi su staništa živih bića. Ptice i njihova gnezda čuvamo tako što ih ne uznemiravamo.', 'Posmatraj živi svet tako da ga tvoje prisustvo ne ometa.'),
  ],
  parovi: [
    { id: 'beograd', levo: 'Beograd', desno: 'glavni grad Srbije' },
    { id: 'sava', levo: 'Sava', desno: 'reka koja se u Beogradu uliva u Dunav' },
    { id: 'dunav', levo: 'Dunav', desno: 'reka koja u Beogradu prima vodu Save' },
    { id: 'avala', levo: 'Avala', desno: 'planina na kojoj je Avalski toranj' },
    { id: 'ada', levo: 'Ada Ciganlija', desno: 'izletište uz Savsko jezero' },
    { id: 'kalemegdan', levo: 'Kalemegdan', desno: 'park uz Beogradsku tvrđavu' },
    { id: 'pobednik', levo: 'Pobednik', desno: 'spomenik na Beogradskoj tvrđavi' },
    { id: 'singidunum', levo: 'Singidunum', desno: 'ime Beograda u rimsko doba' },
    { id: 'knez-mihailova', levo: 'Knez Mihailova', desno: 'poznata pešačka ulica u centru Beograda' },
    { id: 'muzej', levo: 'Narodni muzej', desno: 'ustanova na Trgu republike koja čuva predmete iz prošlosti' },
    { id: 'plan', levo: 'Plan Beograda', desno: 'prikaz rasporeda gradskih ulica i objekata' },
    { id: 'tramvaj', levo: 'Tramvaj', desno: 'vozilo gradskog prevoza koje ide po šinama na ulici' },
  ],
}

export const beograd3 = napraviPidGenerator(BEOGRAD_3)
