import { napraviPidGenerator, type PidCinjenica, type PidOblast, type PidPar } from './zajednicko.ts'

function c(id: string, porodica: string, pitanje: string, tacan: string, netacni: readonly string[], tacnaTvrdnja: string, netacnaTvrdnja: string, objasnjenje: string, hint: string): PidCinjenica {
  return { id, porodica, pitanje, tacan, netacni, tacnaTvrdnja, netacnaTvrdnja, objasnjenje, hint }
}
function p(id: string, levo: string, desno: string): PidPar { return { id, levo, desno } }

const odlikeSrbije: PidOblast = {
  slug: 'pid-odlike-srbije-4', povezivanjeTekst: 'Poveži prirodnu ili društvenu odliku Srbije sa odgovarajućim opisom.',
  cinjenice: [
    c('glavni-grad', 'polozaj-srbije', 'Koji grad je glavni grad Republike Srbije?', 'Beograd', ['Novi Sad', 'Niš', 'Kragujevac'], 'Beograd je glavni grad Republike Srbije.', 'Novi Sad je glavni grad Republike Srbije.', 'Beograd je političko, upravno i jedno od najvećih kulturnih i privrednih središta Srbije.', 'Seti se sedišta najvažnijih državnih ustanova.'),
    c('valuta', 'simboli-i-valuta', 'Koja je nacionalna valuta Republike Srbije?', 'dinar', ['evro', 'forinta', 'kruna'], 'Nacionalna valuta Republike Srbije je dinar.', 'Nacionalna valuta Republike Srbije je kruna.', 'Novčana jedinica Srbije je dinar, čija je oznaka RSD.', 'Seti se kojim novcem plaćamo u Srbiji.'),
    c('himna', 'simboli-i-valuta', 'Kako se zove državna himna Republike Srbije?', 'Bože pravde', ['Tamo daleko', 'Marš na Drinu', 'Vostani Serbije'], 'Državna himna Republike Srbije je „Bože pravde”.', 'Državna himna Republike Srbije je „Marš na Drinu”.', 'Grb, zastava i himna „Bože pravde” jesu državni simboli Srbije.', 'Traži naziv zvanične državne himne.'),
    c('reljef', 'reljef-srbije', 'Koja tvrdnja pravilno opisuje reljef Srbije?', 'U Srbiji postoje i ravničarski i planinski predeli.', ['Cela Srbija je ravnica.', 'Cela Srbija je visoka planina.', 'U Srbiji nema kotlina ni dolina.'], 'Srbija ima ravničarske, brdske i planinske predele.', 'Reljef Srbije je svuda potpuno isti.', 'Panonska nizija preovlađuje na severu, dok su južni i središnji krajevi raznovrsnijeg reljefa.', 'Potraži odgovor koji uvažava raznovrsnost.'),
    c('dunav', 'vode-srbije', 'Koja velika evropska reka protiče kroz Srbiju i Beograd?', 'Dunav', ['Ibar', 'Moravica', 'Toplica'], 'Dunav protiče kroz Srbiju i Beograd.', 'Toplica protiče kroz Beograd.', 'Dunav je međunarodna reka koja protiče i kroz glavni grad Srbije.', 'Seti se reka na ušću kod Beograda.'),
    c('sava', 'vode-srbije', 'Koja reka se u Beogradu uliva u Dunav?', 'Sava', ['Tisa', 'Drina', 'Nišava'], 'Sava se u Beogradu uliva u Dunav.', 'Drina se u Beogradu uliva u Dunav.', 'Ušće Save u Dunav nalazi se u Beogradu.', 'Zamisli pogled sa Kalemegdana.'),
    c('nacionalni-park', 'nacionalni-parkovi', 'Koje zaštićeno područje je nacionalni park Srbije?', 'Tara', ['Ada Ciganlija', 'Zasavica', 'Uvac'], 'Tara je jedan od nacionalnih parkova Srbije.', 'Ada Ciganlija je nacionalni park Srbije.', 'Nacionalni park Tara štiti vredne planinske predele, šume i živi svet.', 'Seti se poznate planine i zaštićenog područja zapadne Srbije.'),
    c('znacaj-suma', 'sume-srbije', 'Zašto su šume važne za prirodu i ljude u Srbiji?', 'čuvaju zemljište, pružaju staništa i utiču na kvalitet vazduha', ['sprečavaju život svih životinja', 'uvek ubrzavaju eroziju', 'nemaju uticaj na vodu i vazduh'], 'Šume pružaju staništa, štite zemljište i utiču na vodu i vazduh.', 'Šume uvek povećavaju eroziju i ne pružaju staništa.', 'Održivo upravljanje šumama čuva njihove ekološke, društvene i privredne vrednosti.', 'Razmisli o korenju, krošnjama i životinjama u šumi.'),
    c('ugrozene-vrste', 'zastita-vrsta', 'Zašto se retke i ugrožene vrste posebno štite?', 'da bi se sprečilo njihovo nestajanje', ['da bi im se smanjilo stanište', 'da bi se prekinuli svi lanci ishrane', 'da bi ostale bez hrane'], 'Retke i ugrožene vrste štite se da bi se sprečilo njihovo nestajanje.', 'Ugrožene vrste štite se uklanjanjem njihovih staništa.', 'Zaštita vrsta obuhvata i očuvanje njihovih staništa i uslova za razmnožavanje.', 'Izaberi cilj koji čuva biološku raznovrsnost.'),
    c('naselja-delatnosti', 'stanovnistvo-i-naselja', 'Zašto su delatnosti ljudi različite u različitim krajevima Srbije?', 'prirodni uslovi i resursi nisu svuda isti', ['svi krajevi imaju potpuno iste uslove', 'naselja nemaju vezu sa okruženjem', 'ljudi ne koriste prirodne resurse'], 'Prirodni uslovi i resursi utiču na delatnosti ljudi.', 'Reljef, vode i resursi ne utiču na delatnosti ljudi.', 'Poljoprivreda, turizam, energetika i druge delatnosti razvijaju se u skladu sa uslovima kraja.', 'Poveži zanimanja sa zemljištem, vodama, rudama ili reljefom.'),
    c('grane-privrede', 'privreda-srbije', 'Koji niz sadrži različite privredne delatnosti zastupljene u Srbiji?', 'poljoprivreda, industrija, trgovina i turizam', ['samo jedna vrsta zanimanja', 'isključivo lov bez drugih delatnosti', 'delatnosti koje ne proizvode ni robu ni usluge'], 'Privredu Srbije čine raznovrsne proizvodne i uslužne delatnosti.', 'Privredu Srbije čini samo jedna delatnost.', 'Prirodni i društveni uslovi utiču na razvoj poljoprivrede, industrije, trgovine, saobraćaja i turizma.', 'Traži odgovor koji pokazuje raznovrsnost.'),
    c('prava-obaveze', 'gradjani-srbije', 'Koji primer istovremeno poštuje prava drugih i građanske obaveze?', 'poštovanje različitosti i dogovorenih pravila', ['vređanje zbog porekla', 'uskraćivanje prava drugima', 'namerno kršenje pravila zajednice'], 'Poštovanje različitosti i pravila doprinosi demokratskim odnosima.', 'Različitosti među građanima treba koristiti za isključivanje.', 'Svi građani imaju prava i obaveze, a suživot počiva na uzajamnom poštovanju.', 'Izaberi ponašanje koje uvažava druge.'),
    c('obnovljiv-izvor', 'prirodni-resursi', 'Koji izvor energije je obnovljiv?', 'sunčeva energija', ['ugalj', 'nafta', 'prirodni gas'], 'Sunčeva energija je obnovljiv izvor energije.', 'Ugalj je obnovljiv izvor energije koji se brzo obnavlja.', 'Sunčeva energija se prirodno stalno obnavlja, dok fosilna goriva nastaju veoma dugo.', 'Traži izvor koji se ne iscrpljuje korišćenjem na ljudskoj vremenskoj skali.'),
    c('stednja-vode', 'odrziva-upotreba', 'Koji postupak čuva resurs čiste vode?', 'popravka slavine koja curi', ['ostavljanje česme otvorene bez potrebe', 'bacanje otpada u reku', 'prekomerno zalivanje tokom najtoplijeg dela dana'], 'Popravka slavine koja curi smanjuje nepotrebnu potrošnju vode.', 'Curenje slavine nema uticaj na potrošnju vode.', 'Čista voda je ograničen i dragocen prirodni resurs.', 'Izaberi postupak koji sprečava rasipanje.'),
    c('lokalni-proizvod', 'odrziva-upotreba', 'Koja može biti prednost kupovine lokalnog sezonskog proizvoda?', 'kraći prevoz i podrška proizvođačima iz okruženja', ['uvek zahteva duži prevoz', 'uvek stvara više ambalažnog otpada', 'onemogućava rad lokalnih proizvođača'], 'Lokalni sezonski proizvod može zahtevati kraći prevoz i podržati lokalnu privredu.', 'Lokalni proizvod uvek mora preći veću udaljenost.', 'Izbor lokalnih proizvoda može smanjiti deo uticaja prevoza i ojačati zajednicu.', 'Uporedi put proizvoda od proizvođača do kupca.'),
    c('reciklirani-proizvod', 'odrziva-upotreba', 'Zašto prednost možemo dati proizvodu od recikliranog materijala?', 'ponovo koristi već izdvojene sirovine', ['zahteva bacanje svih sirovina', 'uvek je napravljen od neobnovljivog goriva', 'sprečava svako razvrstavanje otpada'], 'Proizvod od recikliranog materijala ponovo koristi izdvojene sirovine.', 'Reciklirani proizvod povećava potrebu da se sav otpad baci.', 'Ponovna upotreba materijala može smanjiti otpad i potrebu za novim sirovinama.', 'Poveži proizvod sa značenjem reciklaže.'),
  ],
  parovi: [p('beograd', 'Beograd', 'glavni grad Srbije'), p('dinar', 'Dinar', 'nacionalna valuta Srbije'), p('himna', 'Bože pravde', 'državna himna Srbije'), p('dunav', 'Dunav', 'velika međunarodna reka kroz Srbiju'), p('tara', 'Tara', 'nacionalni park Srbije'), p('fruska', 'Fruška gora', 'nacionalni park u Vojvodini'), p('sunce', 'Sunčeva energija', 'obnovljiv izvor energije'), p('ugalj', 'Ugalj', 'neobnovljiv prirodni resurs'), p('ravnica', 'Panonska nizija', 'pretežno ravničarski sever Srbije'), p('interkultura', 'Interkulturalnost', 'uvažavanje kulturne raznolikosti')],
}

const covek: PidOblast = {
  slug: 'pid-covek-4', povezivanjeTekst: 'Poveži odgovorno ponašanje ili promenu tokom odrastanja sa odgovarajućim opisom.',
  cinjenice: [
    c('prirodno-bice', 'covek-kao-bice', 'Šta znači da je čovek prirodno biće?', 'Njegovo telo ima potrebe i prolazi kroz biološke promene.', ['Ne zavisi ni od vode ni od hrane.', 'Ne pripada živom svetu.', 'Ne menja se tokom odrastanja.'], 'Čovek je prirodno biće čijem telu su potrebni voda, hrana, vazduh, san i kretanje.', 'Čovek kao prirodno biće nema telesne potrebe.', 'Čovek pripada živom svetu i njegovo telo raste i menja se.', 'Razmisli šta je zajedničko ljudima i drugim živim bićima.'),
    c('drustveno-bice', 'covek-kao-bice', 'Šta znači da je čovek društveno biće?', 'Živi, uči i sarađuje sa drugim ljudima.', ['Uvek živi potpuno sam.', 'Ne komunicira sa drugima.', 'Nisu mu potrebne zajednice.'], 'Čovek je društveno biće jer živi i sarađuje u zajednicama.', 'Čovek je društveno biće zato što nikada ne komunicira.', 'Porodica, škola i druge zajednice važne su za razvoj i život čoveka.', 'Seti se grupa kojima pripadamo.'),
    c('svesno-bice', 'covek-kao-bice', 'Koji primer pokazuje da je čovek svesno biće?', 'Razmatra posledice i bira odgovorno ponašanje.', ['Deluje bez ikakvog razmišljanja u svakoj situaciji.', 'Ne može ništa da nauči.', 'Ne razlikuje svoje postupke.'], 'Čovek može da razmišlja o postupcima i njihovim posledicama.', 'Svesno biće ne može da planira svoje postupke.', 'Svest omogućava promišljanje, učenje, planiranje i odgovornost.', 'Izaberi primer u kome osoba razmišlja pre odluke.'),
    c('pubertet', 'odrastanje', 'Šta je tačno za fizičke promene u pubertetu?', 'Javljaju se postepeno i ne počinju kod svih u isto vreme.', ['Kod svih počinju istog dana.', 'Ne razlikuju se ni po čemu među ljudima.', 'Znače da je osoba bolesna.'], 'Promene u pubertetu su deo odrastanja i njihov tempo je individualan.', 'Sve promene u pubertetu kod svih počinju istovremeno.', 'Rast, razvoj i druge telesne promene odvijaju se različitim tempom.', 'Uvažavaj prirodne razlike u razvoju.'),
    c('dnevni-plan', 'dnevne-aktivnosti', 'Šta je najuravnoteženiji dnevni plan?', 'Plan koji uključuje školu, odmor, kretanje, obaveze i san.', ['Plan bez sna.', 'Plan samo uz ekran.', 'Plan bez vremena za obrok i odmor.'], 'Uravnotežen plan uključuje obaveze, odmor, kretanje i dovoljno sna.', 'Dobar dnevni plan ne ostavlja vreme za san.', 'Raspored pomaže da se vreme koristi odgovorno i da se zadovolje različite potrebe.', 'Potraži plan sa ravnotežom aktivnosti.'),
    c('vreme-ekran', 'digitalna-ravnoteza', 'Koji postupak pomaže zdravoj upotrebi IKT uređaja?', 'pravljenje redovnih pauza i dogovoreno ograničenje vremena', ['korišćenje uređaja cele noći', 'odustajanje od kretanja i sna', 'gledanje u ekran bez pauze'], 'Pauze i dogovoreno vreme korišćenja doprinose digitalnoj ravnoteži.', 'Celonoćno korišćenje uređaja doprinosi zdravom snu.', 'Prekomerna upotreba ekrana može potisnuti san, kretanje, učenje i druženje.', 'Izaberi postupak koji čuva i druge dnevne aktivnosti.'),
    c('neprimeren-sadrzaj', 'digitalna-bezbednost', 'Šta dete treba da uradi kada naiđe na uznemirujući ili neprimeren sadržaj?', 'da prekine pregledanje i obrati se odrasloj osobi od poverenja', ['da ga odmah prosledi drugima', 'da odgovori nepoznatoj osobi', 'da ga zauvek čuva kao tajnu'], 'Kod neprimerenog sadržaja treba prekinuti kontakt i zatražiti pomoć odrasle osobe od poverenja.', 'Neprimeren sadržaj treba proslediti drugoj deci.', 'Traženje pomoći je odgovorno ponašanje, a dete nije krivo što je naišlo na takav sadržaj.', 'Izaberi bezbedan korak koji uključuje podršku odraslog.'),
    c('licni-podaci', 'digitalna-bezbednost', 'Koji podatak ne treba javno deliti sa nepoznatim osobama na internetu?', 'lozinku naloga', ['omiljenu boju', 'naziv omiljene knjige', 'mišljenje o filmu bez ličnih podataka'], 'Lozinka je tajni podatak i ne deli se sa nepoznatim osobama.', 'Lozinku je bezbedno javno objaviti.', 'Lozinke, adresa, broj telefona i slični podaci zahtevaju posebnu zaštitu.', 'Traži podatak kojim neko može pristupiti nalogu.'),
    c('jaka-lozinka', 'digitalna-bezbednost', 'Koja je lozinka bezbednija?', 'duga jedinstvena kombinacija koju drugi ne mogu lako pogoditi', ['ime korisnika bez izmene', 'niz 123456', 'ista kratka lozinka za sve naloge'], 'Duga i jedinstvena lozinka teže se pogađa.', 'Niz 123456 je jaka i jedinstvena lozinka.', 'Lozinke treba da budu dovoljno duge, jedinstvene i sačuvane od drugih.', 'Izbegni očigledne i ponovljene lozinke.'),
    c('nepoznata-poruka', 'digitalna-bezbednost', 'Kako postupiti sa sumnjivom porukom nepoznate osobe koja traži lične podatke?', 'ne odgovarati, sačuvati dokaz i obavestiti odraslu osobu od poverenja', ['poslati sve tražene podatke', 'otvoriti svaki link', 'dogovoriti susret bez znanja odraslih'], 'Na sumnjivu poruku ne treba odgovarati niti otvarati nepoznate linkove; treba tražiti pomoć.', 'Nepoznatoj osobi treba odmah poslati lične podatke.', 'Prekid kontakta, čuvanje dokaza i prijava odrasloj osobi povećavaju bezbednost.', 'Ne nastavljaj rizičan kontakt.'),
  ],
  parovi: [p('prirodno', 'Prirodno biće', 'ima telesne potrebe i biološki se menja'), p('drustveno', 'Društveno biće', 'živi i sarađuje u zajednici'), p('svesno', 'Svesno biće', 'razmišlja o postupcima i posledicama'), p('pubertet', 'Pubertet', 'period postepenih promena tokom odrastanja'), p('plan', 'Dnevni plan', 'usklađuje obaveze, odmor i san'), p('pauza', 'Pauza od ekrana', 'deo digitalne ravnoteže'), p('lozinka', 'Lozinka', 'tajni podatak za zaštitu naloga'), p('blokiranje', 'Blokiranje naloga', 'prekid neželjenog digitalnog kontakta'), p('dokaz', 'Snimak ekrana poruke', 'dokaz za prijavu problema'), p('odrasli', 'Odrasla osoba od poverenja', 'podrška kada se pojavi digitalni rizik')],
}

const materijali: PidOblast = {
  slug: 'pid-materijali-4', povezivanjeTekst: 'Poveži postupak ili svojstvo materijala sa odgovarajućim primerom.',
  cinjenice: [
    c('smesa', 'smese', 'Koji primer predstavlja smešu?', 'vazduh', ['čist kiseonik', 'destilovana voda', 'komad čistog zlata'], 'Vazduh je smeša različitih gasova.', 'Vazduh se sastoji samo od kiseonika.', 'Smeša sadrži dve ili više različitih supstanci.', 'Seti se da vazduh sadrži azot, kiseonik i druge gasove.'),
    c('prosejavanje', 'razdvajanje-smesa', 'Kojim postupkom možemo razdvojiti krupnije kamenčiće od sitnog peska?', 'prosejavanjem', ['isparavanjem', 'namagnetisavanjem plastike', 'kondenzacijom'], 'Prosejavanje razdvaja čvrste sastojke različite veličine.', 'Isparavanje razdvaja kamenčiće od peska po veličini.', 'Sito propušta sitnije, a zadržava krupnije čestice.', 'Potraži postupak sa sitom.'),
    c('odlivanje', 'razdvajanje-smesa', 'Kako možemo odvojiti bistru vodu iznad nataloženog peska?', 'pažljivim odlivanjem', ['prosejavanjem kroz krupno sito', 'paljenjem smeše', 'dodavanjem još peska'], 'Pažljivim odlivanjem odvaja se tečnost iznad nataloženog čvrstog sastojka.', 'Odlivanje zahteva sagorevanje smeše.', 'Kada se pesak slegne, gornji sloj vode može se pažljivo odliti.', 'Najpre sačekaj da se čvrste čestice slegnu.'),
    c('cedjenje', 'razdvajanje-smesa', 'Kojim postupkom odvajamo čvrste listiće čaja od napitka?', 'ceđenjem', ['naelektrisavanjem', 'sagorevanjem', 'zaleđivanjem magneta'], 'Ceđenjem se čvrste čestice zadržavaju na cediljci ili filteru.', 'Magnetom odvajamo listiće čaja od vode.', 'Filter propušta tečnost, a zadržava veće čvrste čestice.', 'Seti se cediljke za čaj.'),
    c('isparavanje', 'razdvajanje-smesa', 'Kako iz rastvora slane vode možemo dobiti so?', 'isparavanjem vode', ['prosejavanjem rastvora', 'magnetom', 'odlivanjem rastvorene soli'], 'Isparavanjem vode u posudi ostaje rastvorena so.', 'Prosejavanjem slane vode dobijamo rastvorenu so.', 'Kada rastvarač ispari, čvrsta rastvorena supstanca ostaje.', 'Razmisli koji sastojak može preći u paru.'),
    c('naelektrisavanje', 'elektricitet', 'Šta može da se dogodi kada plastični češalj protrljamo o suvu kosu?', 'može privući sitne komadiće papira', ['postaje trajni izvor vatre', 'pretvara papir u metal', 'gubi svaku mogućnost delovanja'], 'Protrljani plastični češalj može se naelektrisati i privući sitne papiriće.', 'Trljanjem češlja nastaje trajni plamen.', 'Trenje može dovesti do naelektrisavanja predmeta.', 'Seti se jednostavnog ogleda sa češljem i papirićima.'),
    c('provodnik', 'elektricna-provodljivost', 'Koji materijal je obično dobar električni provodnik?', 'bakar', ['guma', 'suvo drvo', 'plastika'], 'Bakar je dobar električni provodnik.', 'Guma je dobar električni provodnik i koristi se za gole žice.', 'Metali poput bakra provode električnu struju, dok guma i plastika služe kao izolatori.', 'Seti se unutrašnjosti električnog kabla.'),
    c('izolator', 'elektricna-provodljivost', 'Zašto su električni kablovi obloženi plastikom ili gumom?', 'jer ti materijali slabo provode električnu struju', ['jer stvaraju dodatnu struju', 'jer su svi metali izolatori', 'da bi kabl lakše goreo'], 'Plastika i guma su električni izolatori.', 'Plastična obloga kabla služi zato što odlično provodi struju.', 'Izolacioni sloj smanjuje mogućnost dodira sa provodnikom.', 'Traži svojstvo koje povećava bezbednost.'),
    c('stednja-struje', 'racionalna-potrosnja', 'Koji postupak štedi električnu energiju?', 'gašenje svetla pri izlasku iz prazne sobe', ['ostavljanje svih uređaja uključenih', 'otvaranje frižidera bez potrebe', 'uključivanje grejanja uz otvorene prozore'], 'Gašenje nepotrebnog svetla štedi električnu energiju.', 'Ostavljanje svetla u praznoj sobi štedi energiju.', 'Racionalna potrošnja znači koristiti energiju kada je potrebna i izbegavati rasipanje.', 'Izaberi postupak koji prekida nepotrebnu potrošnju.'),
    c('magnet', 'magneti', 'Koje predmete običan magnet najčešće privlači?', 'predmete od gvožđa ili čelika', ['sve predmete bez izuzetka', 'isključivo staklene predmete', 'samo drvene predmete'], 'Magnet privlači predmete od gvožđa i čelika.', 'Magnet podjednako privlači drvo, staklo i gvožđe.', 'Magnetna svojstva zavise od vrste materijala.', 'Seti se spajalice i eksera.'),
    c('polovi-magneta', 'magneti', 'Kako deluju isti polovi dva magneta?', 'odbijaju se', ['uvek se privlače', 'pretvaraju se u izolatore', 'prestaju da budu magneti'], 'Isti polovi magneta se odbijaju, a različiti privlače.', 'Isti polovi magneta se uvek privlače.', 'Magnet ima severni i južni pol; njihova međusobna delovanja zavise od kombinacije polova.', 'Uporedi N–N sa N–S.'),
    c('kiseonik', 'sagorevanje', 'Koji sastojak vazduha podržava sagorevanje?', 'kiseonik', ['azot kao jedini uzrok', 'vodena para uvek', 'ugljen-dioksid kao gorivo'], 'Kiseonik iz vazduha podržava sagorevanje.', 'Sagorevanje se nastavlja bez prisustva kiseonika.', 'Za sagorevanje su potrebni gorivo, kiseonik i odgovarajuća temperatura.', 'Seti se zašto se mali plamen ugasi kada mu prekinemo dotok vazduha.'),
    c('pozar', 'zastita-od-pozara', 'Šta dete treba prvo da uradi kada primeti požar?', 'da se udalji na bezbedno mesto i odmah obavesti odrasle ili službu 193', ['da se sakrije bez obaveštavanja ikoga', 'da se vrati po predmete', 'da samo eksperimentiše sa vatrom'], 'Kod požara treba brzo otići na bezbedno mesto i pozvati pomoć.', 'Dete treba samo da gasi veliki požar bez obaveštavanja odraslih.', 'Bezbednost ljudi je najvažnija; vatrogasci se pozivaju na broj 193.', 'Ne rizikuj povratak u opasan prostor.'),
    c('zapaljiva-oznaka', 'zastita-od-pozara', 'Šta upozorava oznaka sa simbolom plamena na proizvodu?', 'da je materijal zapaljiv', ['da je materijal jestiv', 'da je materijal magnet', 'da je materijal uvek bezopasan'], 'Simbol plamena upozorava na zapaljiv materijal.', 'Simbol plamena znači da proizvod treba držati uz izvor toplote.', 'Zapaljive materijale treba držati dalje od plamena i izvora toplote.', 'Poveži znak upozorenja sa prikazanim plamenom.'),
  ],
  parovi: [p('sito', 'Prosejavanje', 'razdvaja čestice po veličini'), p('odlivanje', 'Odlivanje', 'odvaja tečnost iznad taloga'), p('cedjenje', 'Ceđenje', 'filter zadržava čvrste čestice'), p('isparavanje', 'Isparavanje', 'iz rastvora ostavlja čvrstu supstancu'), p('bakar', 'Bakar', 'električni provodnik'), p('guma', 'Guma', 'električni izolator'), p('magnet', 'Magnet', 'privlači gvožđe i čelik'), p('kiseonik', 'Kiseonik', 'podržava sagorevanje'), p('plamen', 'Oznaka plamena', 'upozorenje na zapaljivost'), p('193', 'Broj 193', 'poziv vatrogascima')],
}

const proslostSrbije: PidOblast = {
  slug: 'pid-proslost-srbije-4', povezivanjeTekst: 'Poveži ličnost, događaj ili period iz prošlosti Srbije sa odgovarajućim opisom.',
  cinjenice: [
    c('sloveni', 'dolazak-slovena', 'Ko se doselio na Balkansko poluostrvo u dalekoj prošlosti i čiji su deo bili preci Srba?', 'Sloveni', ['Nemanjići kao narod', 'savremeni industrijalci', 'ustanici iz 19. veka'], 'Sloveni su se doseljavali na Balkansko poluostrvo, a među njima su bili i preci Srba.', 'Sloveni su se na Balkan doselili tek posle Drugog svetskog rata.', 'Doseljavanje Slovena pripada ranom srednjem veku.', 'Smesti događaj pre nastanka države Nemanjića.'),
    c('stefan-nemanja', 'nemanjici', 'Ko se smatra rodonačelnikom vladarske porodice Nemanjića?', 'Stefan Nemanja', ['Karađorđe', 'Miloš Obrenović', 'car Uroš'], 'Stefan Nemanja je rodonačelnik dinastije Nemanjića.', 'Karađorđe je rodonačelnik dinastije Nemanjića.', 'Stefan Nemanja učvrstio je srednjovekovnu srpsku državu i započeo vladarsku lozu Nemanjića.', 'Prezime dinastije upućuje na ime vladara.'),
    c('car-dusan', 'nemanjici', 'Za vreme kog vladara je srednjovekovna srpska država dostigla najveće teritorijalno širenje?', 'cara Dušana', ['cara Uroša', 'Karađorđa', 'kneza Miloša'], 'Za vreme cara Dušana srednjovekovna srpska država dostigla je najveće teritorijalno širenje.', 'Za vreme cara Uroša država Nemanjića dostigla je najveće širenje.', 'Dušan je poneo carsku titulu, a država se tokom njegove vladavine znatno proširila.', 'Seti se vladara sa nadimkom Silni.'),
    c('car-uros', 'nemanjici', 'Sa kojim vladarom se povezuje slabljenje države Nemanjića?', 'carem Urošem', ['Stefanom Nemanjom', 'Karađorđem', 'Milošem Obrenovićem'], 'Sa carem Urošem povezuje se slabljenje države Nemanjića.', 'Car Uroš je započeo Prvi srpski ustanak.', 'Posle smrti cara Dušana velikaši su ojačali, a centralna vlast cara Uroša oslabila.', 'Traži poslednjeg vladara iz glavne loze Nemanjića.'),
    c('turska-vlast', 'zivot-pod-turskom-vlascu', 'Koji primer predstavlja oblik otpora stanovništva pod turskom vlašću?', 'ustanci i hajdučki otpor', ['odricanje od svake borbe', 'industrijalizacija srednjeg veka', 'osnivanje jugoslovenske države'], 'Ustanci i hajdučki otpor bili su oblici suprotstavljanja turskoj vlasti.', 'Prvi svetski rat bio je oblik srednjovekovnog hajdučkog otpora.', 'Otpor je imao različite oblike, od očuvanja identiteta do oružanih buna i ustanaka.', 'Traži pojave iz perioda osmanske vlasti.'),
    c('prvi-ustanak', 'srpski-ustanci', 'Koje godine je počeo Prvi srpski ustanak?', '1804.', ['1815.', '1914.', '1941.'], 'Prvi srpski ustanak počeo je 1804. godine.', 'Prvi srpski ustanak počeo je 1815. godine.', 'Ustanak je podignut 1804. u Orašcu, a za vođu je izabran Karađorđe.', 'To je raniji od dva srpska ustanka.'),
    c('karadjordje', 'srpski-ustanci', 'Ko je bio vođa Prvog srpskog ustanka?', 'Karađorđe Petrović', ['Miloš Obrenović', 'Stefan Nemanja', 'car Uroš'], 'Karađorđe Petrović bio je vođa Prvog srpskog ustanka.', 'Miloš Obrenović bio je vođa Prvog srpskog ustanka.', 'Karađorđe je predvodio ustanak započet 1804. godine.', 'Poveži vođu sa ustankom iz 1804.'),
    c('drugi-ustanak', 'srpski-ustanci', 'Koje godine je počeo Drugi srpski ustanak?', '1815.', ['1804.', '1918.', '1945.'], 'Drugi srpski ustanak počeo je 1815. godine.', 'Drugi srpski ustanak počeo je 1804. godine.', 'Drugi srpski ustanak podignut je u Takovu 1815. godine.', 'Počeo je jedanaest godina posle Prvog ustanka.'),
    c('milos', 'srpski-ustanci', 'Ko je bio vođa Drugog srpskog ustanka?', 'Miloš Obrenović', ['Karađorđe Petrović', 'car Dušan', 'Stefan Nemanja'], 'Miloš Obrenović bio je vođa Drugog srpskog ustanka.', 'Car Dušan bio je vođa Drugog srpskog ustanka.', 'Miloš Obrenović predvodio je ustanak iz 1815. i potom pregovore o autonomiji.', 'Poveži vođu sa Takovom i 1815. godinom.'),
    c('prvi-svetski-rat', 'savremeno-doba', 'Koji događaj pripada početku Prvog svetskog rata?', 'napad Austrougarske na Srbiju 1914. godine', ['početak Prvog srpskog ustanka 1804.', 'dolazak Slovena na Balkan', 'početak Drugog srpskog ustanka 1815.'], 'Austrougarska je napala Srbiju 1914. godine, na početku Prvog svetskog rata.', 'Prvi svetski rat počeo je Prvim srpskim ustankom 1804. godine.', 'Prvi svetski rat trajao je od 1914. do 1918. godine.', 'Traži događaj iz 20. veka.'),
    c('jugoslavija', 'savremeno-doba', 'Posle kog rata je 1918. nastala zajednička jugoslovenska država?', 'Prvog svetskog rata', ['Drugog srpskog ustanka', 'vladavine Stefana Nemanje', 'doseljavanja Slovena'], 'Zajednička jugoslovenska država nastala je 1918, posle Prvog svetskog rata.', 'Jugoslovenska država nastala je za vreme Stefana Nemanje.', 'Kraljevstvo Srba, Hrvata i Slovenaca proglašeno je 1918. godine.', 'Poveži 1918. sa završetkom velikog rata.'),
    c('drugi-svetski-rat', 'savremeno-doba', 'Koji svetski rat je na prostoru Jugoslavije počeo 1941. godine?', 'Drugi svetski rat', ['Prvi svetski rat', 'Prvi srpski ustanak', 'Drugi srpski ustanak'], 'Drugi svetski rat na prostoru Jugoslavije počeo je 1941. godine.', 'Prvi svetski rat na prostoru Srbije počeo je 1941. godine.', 'Napad sila Osovine na Kraljevinu Jugoslaviju dogodio se u aprilu 1941.', 'Uporedi godine 1914. i 1941.'),
    c('redosled', 'hronologija', 'Koji redosled događaja je hronološki ispravan?', 'Nemanjići → srpski ustanci → Prvi svetski rat', ['Prvi svetski rat → Nemanjići → srpski ustanci', 'srpski ustanci → dolazak Slovena → Nemanjići', 'Drugi svetski rat → Prvi srpski ustanak → Nemanjići'], 'Nemanjići prethode srpskim ustancima, a ustanci prethode Prvom svetskom ratu.', 'Prvi svetski rat dogodio se pre države Nemanjića.', 'Lenta vremena pomaže da događaje rasporedimo od starijih ka novijim.', 'Najpre odredi vek svakog događaja.'),
  ],
  parovi: [p('sloveni', 'Sloveni', 'doseljavanje na Balkan u ranom srednjem veku'), p('nemanja', 'Stefan Nemanja', 'rodonačelnik Nemanjića'), p('dusan', 'Car Dušan', 'najveće širenje srednjovekovne države'), p('uros', 'Car Uroš', 'slabljenje države Nemanjića'), p('karadjordje', 'Karađorđe', 'vođa Prvog srpskog ustanka'), p('milos', 'Miloš Obrenović', 'vođa Drugog srpskog ustanka'), p('1804', '1804.', 'početak Prvog srpskog ustanka'), p('1815', '1815.', 'početak Drugog srpskog ustanka'), p('1914', '1914.', 'početak Prvog svetskog rata'), p('1941', '1941.', 'početak Drugog svetskog rata u Jugoslaviji')],
}

export const pidOdlikeSrbije4 = napraviPidGenerator(odlikeSrbije)
export const pidCovek4 = napraviPidGenerator(covek)
export const pidMaterijali4 = napraviPidGenerator(materijali)
export const pidProslostSrbije4 = napraviPidGenerator(proslostSrbije)
export const PID_OBLASTI_4 = [pidOdlikeSrbije4, pidCovek4, pidMaterijali4, pidProslostSrbije4]
